returns current users profile
nss-day-cohort-48/bangazon-CodyJones4235 pull request #27
Opened 2021-08-31 19:47 UTC by CodyJones4235

Description of PR that completes issue here...

## Changes

- Changed line 84 to no longer GET user 4 and instead get the current user logged in 

## Requests / Responses

If this PR contains code that defines a new request/response, or changes an existing one, please put the JSON representations here.

**Request**

GET`/profile` Returns current users profile

**Response**
`Token 9ba45f09651c5b0c404f37a2d2572c026c14669c`
HTTP/1.1 200 OK

```json
{
    "id": 5,
    "url": "http://localhost:8000/customers/5",
    "user": {
        "first_name": "Joe",
        "last_name": "Shepherd",
        "email": "joe@joeshepherd.com"
    },
    "phone_number": "555-1212",
    "address": "100 Endless Way",
    "payment_types": [
        {
            "id": 1,
            "deleted": null,
            "merchant_name": "Visa",
            "account_number": "24ijio68948fj8439",
            "expiration_date": "2020-01-01",
            "create_date": "2019-11-11",
            "customer": 5
        }
    ],
    "recommends": []
}
```
**Request**

GET`/profile` Returns current users profile

**Response**
`Token 9ba45f09651c5b0c404f37a2d2572c026c146694`
HTTP/1.1 200 OK

```json
{
    "id": 5,
    "url": "http://localhost:8000/customers/5",
    "user": {
        "first_name": "Joe",
        "last_name": "Shepherd",
        "email": "joe@joeshepherd.com"
    },
    "phone_number": "555-1212",
    "address": "100 Endless Way",
    "payment_types": [
        {
            "id": 1,
            "deleted": null,
            "merchant_name": "Visa",
            "account_number": "24ijio68948fj8439",
            "expiration_date": "2020-01-01",
            "create_date": "2019-11-11",
            "customer": 5
        }
    ],
    "recommends": []
}
```

## Testing

Description of how to test code...

- [ ] Run migrations
- [ ] Run test suite
- [ ] Seed database
- [ ] using postman run a GET request at this url `http://localhost:8000/profile`  using these two different auth tokens 
`Token 9ba45f09651c5b0c404f37a2d2572c026c14669c`
`Token 9ba45f09651c5b0c404f37a2d2572c026c146694`
note that in the headers tab you should have 1 token set at a time under the authorization key.  You should not have 2 authorization keys in your headers

## Related Issues

- Fixes #22

2021-08-31 20:08 UTC, heymonicakay requested changes
When a reviewer needs additional data to complete the steps to test your code, you must provide them with that data in your PR. 

According to your PR, I need to run a GET request to `/profile` using two different auth tokens in the headers. This isn't quite enough information. Which auth tokens? Do I add both auth tokens to the headers at once? What should I see when I request `/profile` with these auth tokens? How do I know it's working?

Please revise and resubmit!

2021-08-31 20:18 UTC, CodyJones4235 commented
> When a reviewer needs additional data to complete the steps to test your code, you must provide them with that data in your PR.
> 
> According to your PR, I need to run a GET request to `/profile` using two different auth tokens in the headers. This isn't quite enough information. Which auth tokens? Do I add both auth tokens to the headers at once? What should I see when I request `/profile` with these auth tokens? How do I know it's working?
> 
> Please revise and resubmit!

Fixed!

2021-09-01 04:11 UTC, heymonicakay approved these changes

2021-09-01 04:11 UTC, heymonicakay commented
Great work! Thanks Cody!

2021-09-01 04:51 UTC, merged